[package]
name = "redis-conn-adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustis = {version = "0.8.1", features = ["redis-json", "redis-search", "tokio-runtime", "pool"]}
