[package]
name = "gw2-info-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "162fafa0f1b5d9045bf342356671859f0f21c4cc" }
